name: Automatic Tagging
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          description: Latest release of the TechCore Github Action
